-- generated by scripts/generate-auth-stubs-from-dump.py
-- dump에서 참조되는 auth.users UUID를 스텁 사용자로 생성합니다.
-- 주의: 이 사용자는 로그인용 계정이 아니라 FK 충족 목적입니다.

BEGIN;

INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
  created_at, updated_at
)
SELECT
  (SELECT id FROM auth.instances LIMIT 1),
  'd60dc127-ddd6-436f-8189-84c5d47a73cf'::uuid,
  'authenticated',
  'authenticated',
  'migrated-d60dc127-ddd6-436f-8189-84c5d47a73cf@local.invalid',
  '$2a$10$QW5vdGhlckZha2VIYXNoVmFsdWVGb3JNaWdyYXRpb24uLi4=',
  now(),
  '{"provider":"email","providers":["email"]}'::jsonb,
  '{}'::jsonb,
  now(),
  now()
WHERE NOT EXISTS (SELECT 1 FROM auth.users WHERE id = 'd60dc127-ddd6-436f-8189-84c5d47a73cf'::uuid);

COMMIT;
