#!/usr/bin/env python3
from __future__ import annotations

import re
from pathlib import Path

DUMP_PATH = Path('scripts/.migration-output/public_data_sanitized.sql')
OUT_PATH = Path('scripts/sql/insert-missing-auth-users.sql')

REF_COLUMNS = {
    'quote_chat_sessions': ['created_by'],
    'quote_documents': ['uploaded_by'],
    'quotes': ['customer_id'],
    'optimization_runs': ['created_by'],
    'quote_routes': ['created_by'],
    'system_logs': ['user_id'],
    'user_profiles': ['id'],
}

COPY_RE = re.compile(r'^COPY public\.(\w+) \((.*)\) FROM stdin;$')
UUID_RE = re.compile(r'^[0-9a-f-]{36}$')


def collect_uuids(lines: list[str]) -> set[str]:
    uuids: set[str] = set()
    table = None
    indices: list[int] = []

    for raw in lines:
        line = raw.rstrip('\n')

        if table is None:
            m = COPY_RE.match(line)
            if not m:
                continue
            t = m.group(1)
            if t not in REF_COLUMNS:
                table = '__skip__'
                continue
            cols = [c.strip() for c in m.group(2).split(',')]
            indices = [cols.index(c) for c in REF_COLUMNS[t] if c in cols]
            table = t
            continue

        if line == r'\.':
            table = None
            indices = []
            continue

        if table == '__skip__':
            continue

        parts = line.split('\t')
        for i in indices:
            if i < len(parts) and UUID_RE.match(parts[i]):
                uuids.add(parts[i])

    return uuids


def main() -> None:
    if not DUMP_PATH.exists():
        raise SystemExit(f'덤프 파일이 없습니다: {DUMP_PATH}')

    lines = DUMP_PATH.read_text(encoding='utf-8').splitlines(True)
    uuids = collect_uuids(lines)

    out = [
        '-- generated by scripts/generate-auth-stubs-from-dump.py\n',
        '-- dump에서 참조되는 auth.users UUID를 스텁 사용자로 생성합니다.\n',
        '-- 주의: 이 사용자는 로그인용 계정이 아니라 FK 충족 목적입니다.\n\n',
        'BEGIN;\n\n',
    ]

    for uid in sorted(uuids):
        email = f'migrated-{uid}@local.invalid'
        out.append(f"""INSERT INTO auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, raw_app_meta_data, raw_user_meta_data,
  created_at, updated_at
)
SELECT
  (SELECT id FROM auth.instances LIMIT 1),
  '{uid}'::uuid,
  'authenticated',
  'authenticated',
  '{email}',
  '$2a$10$QW5vdGhlckZha2VIYXNoVmFsdWVGb3JNaWdyYXRpb24uLi4=',
  now(),
  '{{"provider":"email","providers":["email"]}}'::jsonb,
  '{{}}'::jsonb,
  now(),
  now()
WHERE NOT EXISTS (SELECT 1 FROM auth.users WHERE id = '{uid}'::uuid);

""")

    out.append('COMMIT;\n')

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(''.join(out), encoding='utf-8')
    print(f'Generated: {OUT_PATH} (users: {len(uuids)})')


if __name__ == '__main__':
    main()
